version: "3.3"
services: 
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
    # database:
    #     build:
    #         context: ./postgres
    #         dockerfile: Dockerfile
    #     environment:
    #         POSTGRES_PASSWORD: Knife444!
    #         POSTGRES_DB: home
    #     ports: 
    #        - "5432:5432"
